import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../theme/app_colors.dart';
import '../widgets/section_title.dart';

class TermsPage extends StatelessWidget {
  const TermsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text('Terms & Conditions', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(vertical: 40, horizontal: 24),
        child: Center(
          child: Container(
            constraints: const BoxConstraints(maxWidth: 900),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const SectionTitle(
                  prefix: 'Terms & ',
                  gradient: 'Conditions',
                  subtitle: 'Official Terms and Conditions for PesaCrow digital escrow services.',
                  align: CrossAxisAlignment.start,
                ),
                const SizedBox(height: 40),
                _buildContentCard(context),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildContentCard(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(32),
      decoration: AppColors.cyberCard(radius: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _section('1. Parties Involved', [
            'The Escrow Agent: PesaCrow (operated by A3s(Absolute Advanced Anonymity Services)), a digital platform providing neutral holding and disbursement services.',
            'The Buyer: Any natural or legal person utilizing PesaCrow to secure a purchase of goods or services.',
            'The Seller: Any natural or legal person utilized PesaCrow to secure payment for the provision of goods or services.',
            'Participating Financial Institutions: Specifically Safaricom M-Pesa, which acts as the underlying payment rail for fund collection and disbursement.',
          ]),
          _section('2. Definitions', [
            '"Escrow Account": The digital wallet or platform-managed record where funds are held until conditions are met.',
            '"Escrowed Funds": The specific monetary amount (KES) deposited by the Buyer for a transaction.',
            '"Disbursement": The act of releasing funds from the Escrow Account to the Seller or Buyer.',
            '"Inspection Period": The timeframe agreed upon for the Buyer to verify the quality of goods/services.',
            '"Business Day": Any day excluding weekends and public holidays in Kenya.',
            '"Deal ID": The unique transaction identifier generated by the PesaCrow platform.',
          ]),
          _section('3. Appointment of the Escrow Agent', [
            'The Buyer and Seller hereby formally appoint PesaCrow as their neutral Escrow Agent. PesaCrow accepts this appointment and agrees to act solely as a facilitator in accordance with the automated logic of the platform and these terms. PesaCrow remains independent and does not represent either party in the underlying commerce.',
          ]),
          _section('4. Description of the Escrowed Property', [
            'PesaCrow facilitates the escrow of Kenyan Shillings (KES).',
            'Deposits: Must be made exclusively via the Buyer’s registered M-Pesa number through the PesaCrow STK Push prompt.',
            'Limits: Minimum and maximum transaction limits apply as dictated by Safaricom M-Pesa regulations and PesaCrow internal policies.',
          ]),
          _section('5. Release / Disbursement Conditions', [
            'Funds are released from the Escrow Account under the following conditions:',
            '1. Mutual Approval: The Buyer confirms receipt and satisfaction of the goods/services through the platform, triggering an immediate release.',
            '2. Seller Proof of Delivery: In specific cases where proof of delivery is undisputed and the inspection period expires without a claim.',
            '3. Dispute Resolution: Upon a final decision by a PesaCrow Admin or an arbitrator in a disputed case.',
            '4. Automatic Expiry: If a deal is cancelled or fails to be approved within the platform\'s defined timeout periods, funds may be returned to the Buyer (less applicable fees).',
          ]),
          _section('6. Fees and Expenses', [
            'PesaCrow charges for its services to ensure platform stability and security.',
            'Service Fees: Calculated as a combination of a fixed percentage and a flat transaction fee (refer to the "Fee Calculator" in-app).',
            'Payment Rails: Standard M-Pesa transaction costs apply for sending and receiving via the platform.',
            'Deduction: Fees are automatically deducted at the point of release or during the initial deposit as specified in the transaction breakdown.',
          ]),
          _section('7. Duties and Responsibilities of the Escrow Agent', [
            'Neutrality: PesaCrow will act as a neutral third party and will not favor one party over another.',
            'Reporting: PesaCrow provides a digital ledger of all transaction statuses within the platform dashboard.',
            'Limitations: PesaCrow is responsible only for the safekeeping of funds and their disbursement according to user instructions; it does not warrant the quality, legality, or suitability of the underlying goods.',
          ]),
          _section('8. Liability and Limitations of Liability', [
            'PesaCrow is not liable for:',
            'Disputes arising from the quality of goods or services provided by the Seller.',
            'Losses due to network failures, Safaricom M-Pesa outages, or incorrect phone number entry by the user.',
            'Indirect, incidental, or consequential damages.',
            'Indemnification: Users agree to indemnify PesaCrow against all claims arising from their use of the platform in violation of these terms.',
          ]),
          _section('9. Dispute Resolution', [
            'In the event of a disagreement:',
            'Mediation: The parties are encouraged to resolve the issue directly through the platform\'s "Dispute" feature.',
            'Escalation: If unresolved after 48 hours, either party may escalate the deal to "Dispute" status.',
            'Admin Decision: PesaCrow Admins will review the evidence (proof of delivery, communication logs) and issue a binding decision.',
            'Legal Action: This Agreement is governed by the laws of the Republic of Kenya.',
          ]),
          _section('10. Termination of Escrow', [
            'The escrow relationship terminates when:',
            'Funds are fully disbursed to the Seller.',
            'Funds are returned to the Buyer.',
            'The deal is cancelled by mutual agreement before the Seller has delivered.',
          ]),
          _section('11. Interest / Investment of Funds', [
            'Escrowed funds held by PesaCrow do not earn interest for the Buyer or Seller. PesaCrow does not invest escrowed funds in high-risk assets.',
          ]),
          _section('12. Representations and Warranties', [
            'Users represent that:',
            'They have the legal capacity to enter this agreement.',
            'The funds used are from legitimate sources.',
            'The transaction does not involve illegal goods (e.g., drugs, weapons, or counterfeit items).',
          ]),
          _section('13. Compliance and Regulatory Clauses', [
            'PesaCrow adheres to Anti-Money Laundering (AML) and Know Your Customer (KYC) regulations. We reserve the right to flag and freeze transactions suspected of fraud or illegal activity and report them to relevant Kenyan authorities.',
          ]),
          _section('14. General Provisions', [
            'Entire Agreement: These terms constitute the full agreement between the parties.',
            'Amendments: Terms may be updated periodically; continued use of the platform constitutes acceptance.',
            'Force Majeure: PesaCrow is not liable for delays caused by "Acts of God," pandemics, or civil unrest.',
          ]),
          _section('15. Miscellaneous', [
            'PesaCrow maintains no interest in the underlying transaction beyond the collection of service fees. Certain clauses, including Liability and Indemnification, survive the termination of this Agreement.',
          ]),
        ],
      ),
    ).animate().fadeIn(duration: 800.ms).slideY(begin: 0.05, end: 0);
  }

  Widget _section(String title, List<String> paragraphs) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 32),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.w900,
              fontSize: 20,
              letterSpacing: -0.5,
            ),
          ),
          const SizedBox(height: 16),
          ...paragraphs.map((p) => Padding(
                padding: const EdgeInsets.only(bottom: 10),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    if (paragraphs.length > 1)
                      const Padding(
                        padding: EdgeInsets.only(top: 6, right: 12),
                        child: Icon(Icons.circle, size: 6, color: AppColors.cyan),
                      ),
                    Expanded(
                      child: Text(
                        p,
                        style: const TextStyle(
                          color: AppColors.textSecondary,
                          fontSize: 15,
                          height: 1.6,
                        ),
                      ),
                    ),
                  ],
                ),
              )),
        ],
      ),
    );
  }
}
